sudo: required
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
language: node_js
node_js:
  - "7"
services:
  - docker
before_install:
- "./tools/travis/setup.sh"
install: true
script:
- "./tools/travis/docker-build.sh"
- "./tools/travis/docker-push.sh"
- "./tools/travis/docker-test.sh"
